### ISSUE TITLE
Devanagari output / AfeySiddham problem

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#13]
Imported from https://github.com/lualatex/luaotfload/issues/406

As context output is faulty too, this should be reported there. 

* Ligatures ending with "yu", "yU" can not be output correctly.
* Vowel symbol "I" can not cope with character change of the parent character with ligatures such as "kyI", "ngI", "nzI".

# Source of the font

https://www.mandaraji.jp/bonji/Fonts/AfeySiddham.otf

# Codes
## LaTeX

~~~~
\documentclass[a4paper]{article}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\newfontscript{Devanagari}{deva,dev2} %ensure deva
\newfontfamily\siddham[Script=Devanagari]{AfeySiddham}
\begin{document}
{\siddham ज्यज्याज्यिज्यीज्युज्यूज्येज्यैज्योज्यौज्यंज्यः\\
म्युम्यूब्युब्यूक्युक्यू\\क्यीख्यी\\न्गन्गिन्गी\\
}
\end{document}

~~~~

## Context

~~~~
\definefont [Deva][file:afeysiddham*devanagari-one]
\starttext
    \Deva ज्यज्याज्यिज्यीज्युज्यूज्येज्यैज्योज्यौज्यंज्यः\\
म्युम्यूब्युब्यूक्युक्यू\\क्यीख्यी\\न्गन्गिन्गी\\
\stoptext
~~~~

# Outputs

## Xelatex output
![image](https://user-images.githubusercontent.com/4047173/46569366-4103bd00-c954-11e8-9a4e-b4cae8052aa7.png)

## context + lualatex output
![image](https://user-images.githubusercontent.com/4047173/46569433-3c8bd400-c955-11e8-9917-c13ce7058564.png)

**Comment by u-fischer** [comment]
@ijaradnam  One of the problems (I'm not sure which of both it is ...) can be resolved by loading the unknown feature `0001` explicitly:

`\newfontfamily\siddham[Script=Devanagari,RawFeature=+0001]{AfeySiddham}`

**Comment by ijaradnam** [comment]
On 2018/10/06 17:56, u-fischer wrote:
>
> I moved the report about afeysiddham to u-fischer#13 and will close here. I didn't know how to describe the ArialUnicodeMS problem. Please add an new issue about it at my github site in a similar way I did for your font. Please take in mind that I know nothing about the script and don't know what are the vowels etc ;-).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thank you for rewriting. The following sample shows the ArialUnicodeMS problem.
```
\documentclass[a4paper]{article}
\usepackage{fontspec}
\defaultfontfeatures{Ligatures=TeX}
\newfontscript{Devanagari}{deva,dev2} %ensure deva
\newfontfamily\chandas[Script=Devanagari]{Chandas}
\newfontfamily\arial[Script=Devanagari]{Arial Unicode MS}
\begin{document}
{\chandas म्रुम्युढिधिभिलिकाङाजाञा}

{\arial म्रुम्युढिधिभिलिकाङाजाञा}
\end{document}
```
