### ISSUE TITLE
luaotfload man pages?

### ISSUE THREAD

**Issue by kberry** [u-fischer/luaotfload#18]
hi ulrike - did you intentionally remove the man pages in the new release? At least luaotfload-tool.1 is very useful, since the package installs that executable ... ? --thanks, karl.

**Comment by u-fischer** [comment]
@kberry  sorry I forgot to create them (I thought as they were unchanged that the step was not necessary but hadn't taken  gitignore into account). I will reupload. Thanks for the report.
