### ISSUE TITLE
Fonts loaded by file name are always loaded from system directory

### ISSUE THREAD

**Issue by khaledhosny** [u-fischer/luaotfload#23]
Suppose I have a font file `amiri-regular.ttf` in the current directory, being used by file name:
```tex
\input luaotfload.sty
\font\amiri={file:amiri-regular.ttf} at 10 pt
\amiri A
\bye
```
I’d expect the file in the current directory to be preferred, then files in the texmf tree, as it is the usual case  with other TeX files. However, I happen to also have a file `Amiri-Regular.ttf` in my system fonts directory and luaotfload is always picking this file.

IMHO, fonts loaded by file name should always be located with kpsathsea and not searched in the font database, and this happens to be what XeTeX does as well.

**Comment by u-fischer** [comment]
While I do understand why you would want this (e.g. to test a newer version), I don't agree with your argumentation. 

luaotfload has its own database as it has to search beside the normal tex trees also external locations like the system fonts directories.  This database is its first and primary resource  to locate (non-legacy) fonts. Using kpathsea first and only if this fails the luaotfload database would be inefficient. 

The file syntax `\font\amiri={file:amiri-regular.ttf}` should naturally also find fonts in system directories. I don't see why it should ignore the majority of user fonts  (and it would break a lot documents if we would change this). 

Fonts in the current directory are a bit of a problem with luaotfload as  
for obvious reasons such fonts shouldn't be recorded in the font database (and the code actively filters the current directory out when creating the database).  

So the `file:`-syntax first checks the database, then triggers the recreation of the database (which slows down the compilation), and only if this fails checks with kpathsea. 

With the bracket syntax `\font\test=[test.ttf]` the situation is better: The recreation is not triggered. But even with ``\font\test=[path/to/local/directory/test.ttf]` the font in the system directory is used. This doesn't look ok. I think I will open a specific issue for this.

Currently your options are imho:
You could put your local font in a texmf tree - the search order should be configurable (https://github.com/u-fischer/lua-font-pond/issues/5) and if not we should correct this.  But this could lead to problems with xetex which often has problems if a font is in two locations. Imho safer would be to rename your local font.

**Comment by khaledhosny** [comment]
But then one can’t write portable documents. If user A and user B compile the above document on two different systems with up to date TeX Live (no local fonts involved at all), they should get identical output. But if user B has a different version of the font installed on the system (usually to be used by non-TeX applications) he would silently get different output with no warning. That is not how people are come to expect things to work in TeX world, where file lookup never crosses the texmf tree border or the current directory.

The font database first and foremost purpose should be resolving font names to file paths, and using for file name is complicating things unnecessarily.

**Comment by u-fischer** [comment]
Well the TeX world is changing here. One main reason for people to use xetex and luatex is that they can handle system fonts directly. I'm quite sure that the majority don't expect that only fonts in texmf trees are used.  That this has an impact on portability is a price they are willing to pay.

The order in which the locations should be searched can be discussed (and probably different users will have different views about it) but taking the system fonts out of the search pathes completly by default is out of question. 

Btw: there is a flag `scan-local` which can be set so that the current working directory is used as a font search location. See the luaotfload-conf documentation.

**Comment by khaledhosny** [comment]
Well, if I’m using the font name, then this is true. But if I take the trouble to find the file name and use it, then the reasonable expectation is that I want to go the TeX way. I don’t know any other system or application that supports loading fonts by file name that would pick arbitrary matching files from the system directories. But that is your call, I can’t argue with that.

**Comment by u-fischer** [comment]
Imho with your expectation "font name -> probably system font wanted" and "file name -> probably texmf font wanted" you are quite alone. I don't see this in the various questions or examples (and I see a lot ...). 

I myself certainly use both variants for both locations.

**Comment by zauguin** [comment]
@khaledhosny If you want to write portable documents which always locate the fonts by kpathsea and ignore system fonts, you can be explicit about it and use the `kpse:` lookup:

```TeX
\input luaotfload.sty
\font\amiri={kpse:amiri-regular.ttf} at 10 pt
\amiri A
\bye
```

**Comment by khaledhosny** [comment]
Thanks. That IIRC, was the original intent of the `file:` lookup, at least when I was still maintaining luaotfload.
