### ISSUE TITLE
Support XeTeX font index syntax

### ISSUE THREAD

**Issue by khaledhosny** [u-fischer/luaotfload#27]
The XeTeX syntax is `[file.ttc:1]` (see page 3 in [XeTeX reference](http://texdoc.net/texmf-dist/doc/xetex/xetexref/xetex-reference.pdf)), but luaotfload only supports `[file.ttc](1)`. The second syntax is already documented in luaotfload manual, but that incompatibility is unfortunate.

(I’d have contributed a patch, but lpeg syntax makes my head spin and I never managed to fully grasp it).

**Comment by u-fischer** [comment]
See https://github.com/u-fischer/luaotfload/issues/28#issuecomment-438959893

**Comment by khaledhosny** [comment]
I don’t think this is quite the same as #28, here luaotfload does not support the XeTeX syntax while supporting an alternative not compatible by XeTeX, rendering the XeTeX compatible syntax useless when one needs to specify font index.
