### ISSUE TITLE
Fully support XeTeX font options (modifiers)

### ISSUE THREAD

**Issue by khaledhosny** [u-fischer/luaotfload#28]
Currently a limited set of XeTeX font options (`/B`, `/AAT` etc.)  are supported, namely the font style ones and only when fonts are specified by name. Since I want to support AAT and Graphite fonts, the other options would be handy, as well as the optical size option. It would be nice, if luaotfload would just parse and store them (e.g. in `specification.modifiers`, even if it does nothing with them itself.

**Comment by u-fischer** [comment]
The goal to support AAT and Graphite fonts is fine. 

But the primary syntax in luaotfload is the `{prefix:font:features}` syntax. This is the one that gets extended by the fontloader and @zauguin has just extended the mode feature to allow something like `file:font.otf:mode=buzz`  to switch to the harfbuzz fontloader.

So if an extension to the syntax is needed it should at first done here, e.g. as a key `type=AAT` and it would be responsability of the "buzzmode" code to pass it to the fontloader correctly. For this it would be useful to have a list of the needed options and an idea about the datastructure you need - luaotfload could either build an "xetex like" syntax directly or pass on a table with the specification and you build it. 

I'm wary to extend the xetex syntax compability. There is nothing in the syntax that is comparable to the `mode=buzz`/`mode=node` key. Which means we would either have to invent some additional syntax feature, or force one mode with fonts loaded with this syntax. Neither of this choices is really appealing. 
Beside this I don't like it very much anyway to have to manage two input syntax on the user level.  One of my goals is to make the xetex syntax unnecessary and push it to the "works to some extend but is deprecated" section (there will be no problems with fontspec here,  the code path there can be changed easily).

**Comment by zauguin** [comment]
I do not think we even need an additional key for AAT/Graphite etc. The difference seems quite similar to the `base`/`node`/`buzz` difference, so the HarfBuzz shaper could just register two additional `mode`s `AAT` and `graphite`.

**Comment by khaledhosny** [comment]
I’m not asking for new options, just extending the currently available XeTeX compatible syntax to be really fully compatible. Currently luaotfload ignore `/AAT` or `/S=xx` options because it does not support them, which is fine. All I’m asking is for them to be parsed and saved in the parsed specification table instead of completely discarded.

Arbitrary `key=value` options are already XeTeX compatible, in the sense that XeTeX will parse an ignore them, but I’m asking for the reverse here; luaotfload parse and save parts of XeTeX syntax it does not currently support while continuing to ignore them.

I have a simple XeTeX compatible parser that I use when not using luaotfload, but I want to be able to use the same syntax with luaotfload, XeTeX and my parser for easy testing and compatibility.

**Comment by u-fischer** [comment]
I think we can save the original input somewhere if this helps testing @zauguin ? It should be only clear that this will not end up as official user syntax for luaotfload. At the end we want there luaotfload syntax (and the type=AAT wasn't meant as a concrete proposition, I only wanted to say that whatever extension we do on the user level it should be done in such a style, the details should be discussed).

**Comment by zauguin** [comment]
@khaledhosny The `/S=` flag is supported by luaotfload and also taken into account by the lookup system.

So let's focus on `/AAT` and friends: I do not see the point in supporting them.
They specify how the font is rendered, not how it is chosen, so by the general design of luaotfload specifications they do not belong in the fontname part but into the feature/options part.
So the only reason for supporting them would be compatibility with XeTeX.
We already are compatible in the way that specifying them never breaks luaotfload, so the question is if we really need a compatible way to select the rendering system. But every user who needs to rely on this already has to specify a special mode to avoid the ConTeXt fontloader, so the user can also use this to specify the rendering system in the luaotfload way.

Example:
Take this XeTeX `\font` call
```tex
\font\lmr "Latin Modern Roman/AAT" at 10pt
```
Even if we add additional support for `/AAT`, this will use the ConTeXt fontloader and therefore will ignore `AAT`.

You want to support (I think)
```tex
\font\lmr "Latin Modern Roman/AAT:mode=buzz" at 10pt
```
But at this point, the user also could just add this information to the feature part:
```tex
\font\lmr "Latin Modern Roman/AAT:mode=aat" at 10pt
```
or
```tex
\font\lmr "Latin Modern Roman/AAT:mode=buzz;kind=aat" at 10pt
```

This is much cleaner from a luaotfload point of view and no additional work for the user.

**Comment by zauguin** [comment]
@u-fischer The original specification is already available in the `specification` field.

**Comment by khaledhosny** [comment]
> @u-fischer The original specification is already available in the `specification` field.

I’m trying to avoid having to re-parse it.

**Comment by khaledhosny** [comment]
> Even if we add additional support for `/AAT`, this will use the ConTeXt fontloader and therefore will ignore `AAT`.

What I currently do it define a macro `\mode`, that can either be `{mode=node;}`, `{mode=harf;}` or `{}` based on whether I’m testing luaotfload, my loader or XeTeX, and then my font definition would look like:
```
\font\lmr "Foo Bar/AAT:\mode;+foo;-bar" at 10pt
```

This way I can write engine and font loader independent font definitions and avoid lots of `\if…\else`. I can imagine luaotfload growing an option in the future to select default mode (if it doesn’t already), then the change would be even more minimal and users can do a something as simple as:
```
\ifluatex\input luaotfload.sty\relax\setluaotfloaddefaultmode{harf}\fi
```

But I can understand if you don’t find this a very important use case.

**Comment by u-fischer** [comment]
I wouldn't say that this isn't an important use case - I know quite well how cumbersome it can be to  compare luaotfload against xetex against context. I'm constantly "translating" font calls between the systems when testing. But this translating shouldn't be done in luaotfload. What you need here is some light-weight variant of fontspec that gives you a high level syntax. This is also important as with luaotfload the prefix-fontname syntax should be tested and not the xetex syntax.

**Comment by u-fischer** [comment]
> @u-fischer The original specification is already available in the `specification` field.

ah. I didn't check, I misunderstood Khaleds description and  so assumed that it is thrown away.
