### ISSUE TITLE
luaotfload and finding lucida-demi for bold

### ISSUE THREAD

**Issue by kberry** [u-fischer/luaotfload#33]
It seems luaotfload apparently doesn't recognize  LucidaBrightOT-Demi.otf as "bold", at least as a system font lookup. I'm not sure about filename lookups; the .fontspec file explicitly specifies it as the BoldFont, so it should work, but ...

What can we do to fix this? We cannot change the name of the font, either internally or the filename -- "Demi" was chosen carefully B&H and represents their intention. But we can provide extra information in any feasible way to make it work.

Help? Thanks.

**Comment by u-fischer** [comment]
Can you show some code how you are trying to call/use the font and what doesn't work?

**Comment by kberry** [comment]
With Lucida Bright fonts installed as system fonts. On GNU/Linux (users on Mac and, as I recall, Windows, report the same thing; it's not os-specific), I can run:
$ fc-list :scalable=true family | grep 'Lucida Bright'
and output is 
Lucida Bright OT

The four fonts involved being
LucidaBrightOT.otf
LucidaBrightOT-Italic.otf
LucidaBrightOT-Demi.otf
LucidaBrightOT-DemiItalic.otf

As I recall, you did buy a Lucida font license so have the fonts. In any case, it's not about the content of the fonts per se; taking any font family and renaming the bold variant to "Demi" should yield the same results.

Anyway, given those system fonts, I run a basic document, say xlsys.tex:

\documentclass{article}
\usepackage{fontspec}
\setmainfont{Lucida Bright OT}
\begin{document}
roman \textit{italic} \textbf{bold \textit{bold-italic}}
\end{document}

Running with:
xelatex xlsys.tex -> all four fonts correctly show up.

Running with:
lualatex xlsys.tex -> roman and italic are correct, but bold and bold-italic are not found (fall back to regular roman and italic):

Warning msgs from lualatex:
LaTeX Font Warning: Font shape `TU/LucidaBrightOT(0)/bx/n' undefined
(Font)              using `TU/LucidaBrightOT(0)/m/n' instead on input line 5.


LaTeX Font Warning: Font shape `TU/LucidaBrightOT(0)/bx/it' undefined
(Font)              using `TU/LucidaBrightOT(0)/bx/n' instead on input line 5.

No .fontspec file is being read. (If I do cause lucidabrightot.fontspec to be read, all the fonts are found. But this should not be necessary with system font lookups.)

FWIW, my recollction is that years ago, Hans had some kind of special case in his original code to recognize the Lucida "Demi" as the bold variant. Then he took the special case out, and it has never been recognized since without some kind of special pains.

If something can be done, that'd be great. Thanks.

**Comment by u-fischer** [comment]
I don't have license for the fonts. But I looked a bit in the fontspec and the luaotfload code. fontspec relies on the /B modifier to find the bold font. This modifier relies on the `families` table in the names database, which contains mappings from the core font to the bold and italic variants. 

When building this table luaotfload uses the following synonyms for bold: 

~~~~
local bold_synonym = {
    bold  = true,
    black = true,
    heavy = true,
}

~~~~

While it is would be naturally possible to add `demi` to this synonyms I'm not sure if this would be a good idea. I fear that it would have bad side effects on fonts which have a demi *and* a bold (heavy) variant.

**Comment by kberry** [comment]
extract from texmf-var/luatex-cache/generic/names/luaotfload-names.lua.gz attached.

demi could be recognized as bold if the font has no other bold. Or, as I said at the beginning, we could somehow add the information in another file for luaotfload. The point is that it seems wrong for xelatex to do the right thing and lualatex not to (I understand why they behave differently, but that doesn't alter the outcome ...).

Thanks for looking at it.

[lunames.txt](https://github.com/u-fischer/luaotfload/files/2794060/lunames.txt)

**Comment by kberry** [comment]
It worked for me. Thanks! (It's hard to be sure my testing is the same as the real thing by other users, but I guess we'll see.)

**Comment by u-fischer** [comment]
Good. I will probably update this week. It also looks as if the incompability with luatex 1.07 is gone in the newest context fontloader, so I will update it too. If you can/want to test: the branch v2.9502-2019-01-25 contains currently the code of the planed update.
