### ISSUE TITLE
better error message for non existing fonts ...

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#35]
~~~~
\documentclass{article}
\usepackage{fontspec}
\setmainfont{blub}
\begin{document}

\end{document}
~~~~

leads to 

~~~~
luaotfload | db : Reload initiated (formats: otf,ttf,ttc); reason: "Font blub not found."....ad/texmf/tex/luatex/luaot
fload/fontloader-2019-01-28.lua:27119: attempt to index a nil value (upvalue 'd
escriptions').
<to be read again>
\scan_stop:
l.46 \begin
         {document}
~~~~

This should be improved.
(tested with current fontloader in branch v2.9503-2019-01-28, but imho it is also so with the current ctan version).

**Comment by u-fischer** [comment]
I found the reason. I had a file `blub.tex` in the current folder and luaotfload seems to use it as the last try. I know remember about another issue where a tex-file interfered https://github.com/lualatex/luaotfload/issues/269.   Is there any benefit for tex-files being in the lookup chain?

**Comment by zauguin** [comment]
@u-fischer Can you try my [dev branch](/zauguin/luaotfload/tree/dev)? This should be fixed there. There was no benefit, it was only a byproduct of using a common wrapper for kpathsea.

**Comment by u-fischer** [comment]
@zauguin  sure will do it. On which branch/fontloader is it based?

**Comment by zauguin** [comment]
Is is your `dev` branch plus some commits I yet have to write a PR for.

**Comment by u-fischer** [comment]
@zauguin  I tried your dev branch, both unchanged and merged with the newest fontloader and had no problems. The testsuite passed and the chess fonts works too. I only see at the begin of the compilation on the terminal a output of a table starting with 

~~~~
t={
 ["file"]=load("\27LuaS\0\25ô\13\
~~~~

Is this expected?

**Comment by u-fischer** [comment]
Resolved hopefully with v.2.95
