### ISSUE TITLE
Falling back to luaotfload in custom readers

### ISSUE THREAD

**Issue by khaledhosny** [u-fischer/luaotfload#37]
In my `fonts.readers.harf`, I want to fallback to luaotfload for fonts I can not handle. This is helpful especially when forcing all fonts to use `mode=harf` unconditionally. Suppose a font was defined as:
```
\font\test="[cmr10.tfm]:mode=harf"
```

I want to send that font back to luaotfload to load it itself, instead of adding special handling for each font format I don’t support.

I was expecting returning `nil` to do this, but it doesn’t. Alternatively, having a supported way for calling the function that luaotfload sets for `define_font` call back would be good enough.

**Comment by zauguin** [comment]
To call the function, luaotfload (or anyone else) sets for `define_font`, just use `callback.find"define_font"("My awesome font", -1000)` or similar. This is documented in the LuaTeX manual and therefore I would consider it supported.

**But** please do not use this to fall back to another reader. Whenever I encounter software doing something like this I feel cheated: If I set `mode=harf`, I do want to use the mode `harf`, I explicitly do not want the default mode. Also I do not want my system to assume it knows better than me what to do.

**Comment by khaledhosny** [comment]
This is more for the cases where luaotfload’s mode is forced to `harf` by default (e.g. using a conf file), and what I want to do is to check that if the mode is explicitly set and the value is not `harf` then load it like luaotfload would have normally done.

**Comment by zauguin** [comment]
@khaledhosny If the config file sets `mode=harf` and you explicitly set another mode, shouldn't the default mode be ignored anyway? Otherwise that seems to be the real issue here, the default should never overwrite explicit settings IMO.

**Comment by zauguin** [comment]
Also setting `mode` through the config files sounds like a bad idea because the mode is not supposed to be the same for different formats. This sounds like you are really trying to do something else. Do you want to change the default loader used for specific font formats?

**Comment by khaledhosny** [comment]
You are right, I don’t need to handle explicit mode, luaotfload takes care of that and I never see the font.

What remain is https://github.com/khaledhosny/luahbtex-harf/issues/30, if I set mode in config file I still get TFM and other formats luaotfload supports but I don’t (Type 1, lua fonts, etc.) and I need a generic way to handle them and not break packages that load such fonts.

**Comment by khaledhosny** [comment]
Using `callback.find"define_font"` will just enter into an infinite loop because it keeps calling back my `font.readers.harf` function.

**Comment by zauguin** [comment]
I think khaledhosny/luahbtex-harf#30 should be fixed in fontspec, maybe as part of wspr/fontspec#342: Whenever `Renderer=` is used, the `mode=` should be passed even to the trial fonts. Maybe fontspec could generally be changed to query luaotfload for the information queried through trial fonts when LuaTeX is used but we will have to talk with @wspr about this.

Until then you could use

    font.readers.otf = font.readers.harf
    font.readers.ttf = font.readers.harf
    font.readers.ttc = font.readers.harf

to set Harfbuzz as the default renderer for OpenType fonts without affecting other font formats. We might want to add an official interface for this, but I am not sure how this should look.
Some new config entry probably...

**Comment by u-fischer** [comment]
Hm. I don't have time to check the details, but if a user calls e.g. a legacy tfm font when "mode=harf" is active (how ever this happened) and mode=harf doesn't support legacy tfm fonts then there  are only two option: the harf-reader can quit with a large error, or fall back to another reader (perhaps with a large warning).  Imho the second option is better.

**Comment by khaledhosny** [comment]
I guess fixing fontspec is the best way forward for the time being.
