### ISSUE TITLE
tlig em dash ligature is broken 

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#44]
(moved from dev-luatex)

`---` doesn't give an em-dash if there are no spaces around it (but curriously a hyphen before change this). 

context doesn't have a problem. The problem is still there in the newest branch (v2.9603-...). 
It works with texlive2017 (and the same fontloader), which seems to imply some engine change but older cache content could play a role here too.

~~~~

\input luaotfload.sty
\font\test={name:texgyreheros:+tlig;}\test

em dashes---these % gives en-dash

em-dashes---these % gives em-dash

en dash--these %ok

\bye

~~~~

![image](https://user-images.githubusercontent.com/4047173/53284828-9a308980-3759-11e9-88ea-804841b56501.png)

**Comment by zauguin** [comment]
I can not reproduce the difference in behaviour depending on the hyphen but always get a en-dash. Apart from that, the regression was introduced in c98b44c1ae8b9ffe1d802963d74a4253a414acc0 which only updated the fontloader. Also it can be reproduced using the plain fontloader:

```tex
\input plainfontloader.tex
\font\test={file:texgyreheros-regular.otf:+tlig;mode=node;}\test

dashes-these % gives dash

dashes--these % gives en-dash

dashes---these % gives en-dash
\bye
```

@u-fischer This seems like an upstream bug. I currently do not have a working ConTeXt install to investigate, so I can't tell why ConTeXt isn't affected. Is ConTeXt using `mode=node` or `mode=base` for this font?

**Comment by u-fischer** [comment]
Ah, good, not our fault ;-). With mode=node I see the problem too. I sent a message to the context list, but I don't want to wait until this is fixed, but will try to upload new version anyway.

**Comment by u-fischer** [comment]
@zauguin  it looks as if we should put `\automatichyphenmode=1` (or the lua equivalent `tex.automatichyphenmode=1` ) somewhere. Do you have suggestion for a sensible place? (Hans will put it in the plain fontloader too, but I don't know yet, where exactly).

**Comment by zauguin** [comment]
I think the default value of `\automatichyphenmode` should be made by the format, so in the LaTeX kernel.
If you want to set this in luaotfload through, I think luaotfload-init.lua would be the best location: Add a third entry in `init_post_actions`.

**Comment by u-fischer** [comment]
@zauguin  I agree, \XeTeXdashbreakstate is set in the format, and so the luatex setting should there be too. I'm just discussing it on the team list.

**Comment by schlcht** [comment]
Following a report about a [microtype problem](https://github.com/schlcht/microtype/issues/61), I came across this issue. @u-fischer, you said you'd had discussions with the latex team about adding `\automatichyphenmode=1` to the format(s), has this been dismissed or simply forgotten? I gather from the conversation on the [luatex list](https://tug.org/pipermail/luatex/2026-January/008147.html) about this issue that context sets this in the format, maybe (la)tex should follow suit?
