### ISSUE TITLE
use of microtype crashes with texlive version 50131

### ISSUE THREAD

**Issue by ArTourter** [u-fischer/luaotfload#46]
I reported it to the texlive mailing list (https://tug.org/pipermail/tex-live/2019-February/043145.html)

but basically with the following code:

```latex
\documentclass{article}
\usepackage{fontspec}
\usepackage{microtype}
\begin{document}
test
\end{document}
```

I get the following error when compiled with lualatex:

```
(/usr/local/texlive/2018/texmf-dist/tex/latex/microtype/microtype-luatex.def...
exlive/2018/texmf-dist/tex/latex/microtype/microtype.lua:145: attempt to
call f
ield 'warning' (a nil value)
stack traceback:
        ...exlive/2018/texmf-dist/tex/latex/microtype/microtype.lua:145: in
main chunk

        [C]: in function 'require'
        [\directlua]:1: in main chunk.
l.59 \MT at lua{require("microtype")}
```

reverting to 49978 works fine.

**Comment by zauguin** [comment]
See https://tex.stackexchange.com/questions/476740/microtype-error-with-lualatex-attempt-to-call-field-warning-a-nil-value:
This is a microtype bug exposed by the latest luaotfload update.
While we are waiting for a microtype fix, the problem can be avoided by adding

`\usepackage{luatexbase}`

before loading microtype.

**Comment by ArTourter** [comment]
Thanks @zauguin 
That indeed fixes it.
Cheers
