### ISSUE TITLE
Optima.ttc works only when using full names but not / shorthands

### ISSUE THREAD

**Issue by FrankMittelbach** [u-fischer/luaotfload#47]
Trying to use Optima (.ttc) on OSX but it doesn't seem to find the Bold or Italic etc if the `/` notation is used with LuaTeX, eg

~~~~
\documentclass{article}

\begin{document}
\font\1="Optima" at 12pt\relax
\1\fontname\1

\font\2="Optima/I" at 12pt\relax
\2\fontname\2

\font\3="Optima Italic" at 12pt\relax
\3\fontname\3

\font\2="Palatino" at 12pt\relax
\2\fontname\2

\font\3="Palatino/I" at 12pt\relax
\3\fontname\3

\font\4="Palatino Italic" at 12pt\relax
\4\fontname\4
\end{document}
~~~~

It works correctly with the long names. For Palatino it works in both forms. And it does work correctly when XeTeX is used.

The entries in the names.lua.gz look about the same, so I have clue why it fails for Optima:

~~~~
  {
   ["basename"]="Optima.ttc",
   ["conflicts"]={
    ["barename"]=2142,
    ["basename"]=2142,
   },
   ["fontname"]="optimaitalic",
   ["format"]="ttc",
   ["fullname"]="optimaitalic",
   ["fullpath"]="/System/Library/Fonts/Optima.ttc",
   ["index"]=2144,
   ["italicangle"]=-12,
   ["location"]="system",
   ["pfmweight"]=400,
   ["plainname"]="Optima Italic",
   ["size"]=false,
   ["subfamily"]="italic",
   ["subfont"]=3,
   ["version"]="13.0d1e2",
   ["weight"]="normal",
   ["width"]=5,
  },
~~~~
~~~~
   ["basename"]="Palatino.ttc",
   ["conflicts"]={
    ["barename"]=2249,
    ["basename"]=2249,
   },
   ["familyname"]="palatino",
   ["fontname"]="palatinoitalic",
   ["format"]="ttc",
   ["fullname"]="palatinoitalic",
   ["fullpath"]="/System/Library/Fonts/Palatino.ttc",
   ["index"]=2250,
   ["italicangle"]=-12,
   ["location"]="system",
   ["pfmweight"]=400,
   ["plainname"]="Palatino Italic",
   ["psname"]="palatinoitalic",
   ["size"]=false,
   ["subfamily"]="italic",
   ["subfont"]=2,
   ["version"]="13.0d1e2",
   ["weight"]="normal",
   ["width"]=5,
  },
~~~~
The only difference that I can see is that the "familyname" is missing in the optima entry. Maybe that's the reason, but I have no idea why that is not set. Might be related to https://github.com/lualatex/luaotfload/issues/392

**Comment by u-fischer** [comment]
@FrankMittelbach  Could you please test if https://github.com/u-fischer/luaotfload/pull/48 resolves the problem?

**Comment by FrankMittelbach** [comment]
seems to work (once I understood how to force a db reload :-) ) Thought that --force is enough but it isn't it needs --update too.

thanks, for the speedy fix

**Comment by FrankMittelbach** [comment]
With the patch installed the following document hangs in luatex (works with XeTeX), without the patch it works in both engines

```
\documentclass{article}

%\usepackage{trace}


\usepackage[sfdefault]{FiraSans}


\begin{document}

\def\txfigures{\addfontfeature{Numbers=OldStyle}}
\def\lnfigures{\addfontfeature{Numbers=Lining}}
\def\tbfigures{\addfontfeature{Numbers=Monospaced}}
\def\prfigures{\addfontfeature{Numbers=Proportional}}


\txfigures   12345 (text/oldstyle)

\tbfigures   12345 (tabular/monospaced)

\lnfigures   12345 (lining)

\prfigures   12345 (proportional)


X\oldstylenums{12345}X


\end{document}
```

**Comment by u-fischer** [comment]
@FrankMittelbach  It compiles fine for me - and I have the patch installed and in use. But the first compilation took quite some time as the package loads lots of variants. Can you check during the compilation in the luatex-cache fonts folder if lua/luc files are created? What happens if you load only one font with `\usepackage{fontspec}\setmainfont{firasans}`?

**Comment by FrankMittelbach** [comment]
woah, you said I should have got me a coffee, but it looks that one wasn't enough :-). It does indeed compile but I needed more than 2 coffees. Sorry for the noise.
