### ISSUE TITLE
Explicitely loading of bitmap font does not work

### ISSUE THREAD

**Issue by pali** [u-fischer/luaotfload#50]
*Cloned from https://github.com/lualatex/luaotfload/issues/421*

Simple tex file:

```tex
\input plain
\input luatexiniconfig.tex
\input luatex85.sty
\input luaotfload.sty
\pdfpkresolution=600
\font\bitmap=file:cmr10.tfm:reencode=8a.enc;bitmap=yes
\bitmap test
\bye
```

Bitmap font is explicitely requested, but in luatex log can be found that cmr10.pfb file is used. Also pdffonts say that final PDF file has Type 1 (and not Type 3).

**Comment by zauguin** [comment]
This can not be changed in luaotfload AFAICT, the LuaTeX engine does not support loading bitmap fonts if a applicable map entry is present.

If we would want to implement this, we would have to effectively invoke
```tex
    \pdfextension mapline{-cmr10 ...}
```
which would break all following attempts to load the normal outline version.
So I think user who want to load the bitmap version should use `mapline{-` on their own.

But I am not even sure if that is the intended behaviour of `bitmap=yes`: I think the option does not tell luaotfload to load a bitmap font, it only informs LuaTeX that the loaded font will be a bitmap font. (Detecting this is quite hard and they are handled differently)

**Comment by pali** [comment]
Is not luaotfload replacing usage of mapfile/mapline?

But important question is what `bitmap=yes` option is doing? Seems that documentation for it is missing.

**Comment by zauguin** [comment]
@pali Bitmap fonts are treated as legacy fonts in LuaTeX, they can not be used through the new font system. So for them, the traditional system with mapfiles etc. is still used.

Now what is `bitmap=yes` doing? For the offically intended behaviour, you have to ask the Context team, but effectively it is only related to how `reencode` works:

Normally `reencode` is implemented in a way which requires Type1 fonts. It has to be able to read a `pfb` file to get glyph names and it changes the way in which they are indexed. `bitmap=yes` switches to another system which is compatible with bitmap fonts.

So `bitmap=yes` is required if you want `reencode` to work with bitmap fonts, but it does *not* switch to the bitmap font if a Type1 font is found too. The implementation strongly suggests that this is the intended behaviour.

**Comment by pali** [comment]
So... I think I get it now. When using mapfiles you need to have enc file. And when you do not specify enc file then luatex/luaotfload needs to generate encoding vector for it. Type 1 pfb fonts have different format as metafont pk fonts so you need to instruct luatex/luaotfload how encoding vector is going generated, right? Therefore `bitmap=yes` parameter does not try to parse pfb file, but rather needs to use enc file.

**Comment by pali** [comment]
Anyway, this behavior "use font of any format" is bad. It depends on what is installed in system or in current directory. I would really like to see option "use font of **this** format and if is not available then stop and report error". If this cannot be implemented in luaotfload, cannot be luatex itself extended to *deterministic* mode when you specify "I want font of *this* format"? (E.g. bitmap pk file / generate it from metafont source)

**Comment by pali** [comment]
Now looking into luatex.pdf documentation and in section *5.2 Real fonts* is written that `type3` is valid value for `format` and means `this is a bitmapped (pk) font`. So cannot luaotfload really force usage of bitmap font?

**Comment by zauguin** [comment]
@pali The description in the LuaTeX documentation about this is at least misleading, but specifying Type3 there does not help:
For a Type3 font, `encodingbytes` has to be `1`. (This can not be changed, the PDF format does not support wide Type3 fonts)
But if `encodingbytes` is not `2`, the `format` is ignored.
So you can certainly set `format` to `Type3`, but LuaTeX will still use the Type1 font. LuaTeX *could* be changed to behave differently in this case, but I do not think that the LuaTeX team is very interested in developing new features for Type3 fonts.

Anyway, you can enforce the use of a Type3 font by "hiding" the Type1 fonts: Just use `\pdfextension mapline{-...}`, for example

```tex
\input luaotfload.sty
\pdfvariable pkresolution=600
\pdfextension mapline{-cmr10 XXX}
\directlua{ % Fix a unrelated bug in reencode
table.setmetatableindex(fonts.helpers.commands.char, function(t,k)
  local v = { "char", k }
  t[k] = v
  return v
end)
}
% You should specify the right encoding here, cmr10 has encoding OT1 or 7t
\font\bitmap=file:cmr10.tfm:reencode=7t.enc;bitmap=yes
\bitmap test
\bye
```
will always give you a bitmap version of cmr10.

**Comment by pali** [comment]
> So you can certainly set `format` to `Type3`, but LuaTeX will still use the Type1 font. LuaTeX *could* be changed to behave differently in this case, but I do not think that the LuaTeX team is very interested in developing new features for Type3 fonts.

I think this is a bug, rather a new feature. Anyway, if team is not interesting in developing fix for it would they be willing to include/accept fix created by me? (I'm guessing that it should not be hard to add some conditions into C/WEB code to accept `format` argument)

> Anyway, you can enforce the use of a Type3 font by "hiding" the Type1 fonts: Just use `\pdfextension mapline{-...}`

https://github.com/lualatex/luaotfload/issues/421#issuecomment-475052538 That is possible for use case 1. but not easily for 2. :-(

> The description in the LuaTeX documentation about this is at least misleading

Can you at least fix documentation? Because this is first thing to which developers look when they need to configure something not-so-common or need to debug some problem.

> `% Fix a unrelated bug in reencode`

And what is this?

**Comment by u-fischer** [comment]
@pali  we are maintaining luaotfload here, not luatex. So if you have feature request for luatex write to the luatex mailing list, similar for problems with it documentation. For suggestion for the internal fontloader: as it is imported from context, the best place to ask for additions is the context mailing list.

**Comment by zauguin** [comment]
> I think this is a bug, rather a new feature. Anyway, if team is not interesting in developing fix for it would they be willing to include/accept fix created by me? (I'm guessing that it should not be hard to add some conditions into C/WEB code to accept format argument)

@pali I am just guessing here, if you want a real answer ask the LuaTeX team directly. During the last year I send them multiple fixes and got very different responses. At least do not expect a quick change, the version for TeXLive 2019 just entered a "code freeze, major bug fixes only" according to https://tug.org/texlive/.

> lualatex#421 (comment) That is possible for use case 1. but not easily for 2. :-(

The whole problem only appears for Type 3 fonts, so you could use this to get the Type 3 font and then load the Type 1 font without relying on map files. This currently doesn't work through, because the fontloader caches the first font. But this is only a fontloader problem.

> Can you at least fix documentation? Because this is first thing to which developers look when they need to configure something not-so-common or need to debug some problem.

That is the responsibility of the LuaTeX team.

> > `% Fix a unrelated bug in reencode`
>
> And what is this?

As the comment says, it is a work-around for a unrelated bug in reencode.
