### ISSUE TITLE
newest context files breaks ...

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#64]
in branch v2.9805-2019-20-06 loading fails directly with 

~~~~
fload/luaotfload-init.lua:639: attempt to index a nil value (field 'handlers')
stack traceback:
	...aotfload/texmf/tex/luatex/luaotfload/luaotfload-init.lua:639: in upvalue 'in
it_main'
	...aotfload/texmf/tex/luatex/luaotfload/luaotfload-init.lua:810: in function 'l
uaotfload-init.lua.main'
	...aotfload/texmf/tex/luatex/luaotfload/luaotfload-main.lua:286: in field 'main
'
	[\directlua]:1: in main chunk.
<everyjob> ...ring \\def\string \\encodingdefault{OT1}')end }
                                                  \let \f@encoding \encoding...
l.1 
  % !Mode:: "TeX:DE:UTF-8:Main"
~~~~

**Comment by zauguin** [comment]
@u-fischer A typical packaging problem: One of the fontloader files, `basics-chr.lua`, returns something. That's perfectly normal for a modern Lua module, but it is not compatible with the fontloader packaging system. So the `unpackaged` is not affected. We could report the line

    return characters.indicgroups

in `basics-chr.lua` upstream as a bug, but I think it would be better to fix the packaging. I fixed the problem in [a branch](/zauguin/luaotfload/tree/newpackage) for fontloaders packed by `mkimport`, but the problem still persists in `reference`. That's probably copied from ConTeXt?

**Comment by u-fischer** [comment]
fontloader-reference.lua is a copy of the luatex-fonts-merged.lua.  I will report that it is broken. The test suite runs also on the reference fontloader, so it is not good if it doesn't work ;-) I removed the `return` line from the fontloaders and will run the test suite and then try with your branch.
