### ISSUE TITLE
improve handling of missing chars

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#65]
mode=node simply drops missing chars, while xetex and harf-mode either insert spaces or the "missing char" glyph. I think the later is better and it should be done if possible by mode=node too. 

~~~~
\documentclass{article}
\begin{document}
x\SS y
\end{document}
~~~~

## output with lualatex (mode=node)

![image](https://user-images.githubusercontent.com/4047173/60265785-dd0c9480-98e6-11e9-8604-03fd625744a6.png)

## output with harftex (+ \usepackage{harfload} or lua-code in the format) or xelatex

![image](https://user-images.githubusercontent.com/4047173/60265828-f9103600-98e6-11e9-827b-37473951cd83.png)

## output of a libertinus example with harftex

![image](https://user-images.githubusercontent.com/4047173/60266267-024dd280-98e8-11e9-8997-74679a53041a.png)

**Comment by khaledhosny** [comment]
HarfTeX (and I think XeTeX) always inserts `.notdef` glyph (glyph at index 0 in the font), but it is a blank glyph in some fonts (which is not-so-good idea, they are usually fonts made by TeX people).
