### ISSUE TITLE
difficulty using glyphs in the Corporate Use or Microsoft Symbol Areas

### ISSUE THREAD

**Issue by mewtant** [u-fischer/luaotfload#7]
With version 2.9 of luaotfload, it has become more difficult to use glyphs in the Corporate Use and similar areas.  For example, the `\fontchar` macro no longer gives the desired result.  See https://tex.stackexchange.com/q/453224 for more details.

**Comment by u-fischer** [comment]
I asked on the context list: https://www.mail-archive.com/ntg-context@ntg.nl/msg89146.html

**Comment by u-fischer** [comment]
Same problem reported by Claudio Beccari:

~~~~~
\documentclass{book}

\usepackage{libertine}

\begin{document}

First hit this key sequence:\LKeyShiftX{H}

Then hit these keys one by one:
\LKey{E}\LKey{L}\LKey{L}\LKey{O}\LKeySpace\LKey{W}\LKey{O}\LKey{R}\LKey{L}\LKey{D}

And finally hit the \LKeyEnter\ key.

You should now see the phrase ``Hello world'' on your screen.

\end{document}
~~~~~

## Current Output:

![image](https://user-images.githubusercontent.com/4047173/46282880-00cac600-c573-11e8-909c-e9df8d4b0092.png)


## Expected Output

![image](https://user-images.githubusercontent.com/4047173/46283030-82baef00-c573-11e8-9dd0-8614c1763cea.png)

**Comment by u-fischer** [comment]
The generic fontloader moved "all private chars in the font to a dedicated private range" and so broke the access of this glyphs. If this change is permanent all packages and documents which access such glyphs will have to adapt their code.  


## Currently available work-arounds

### use older fontloader

* Get the 2018-07-20 (or 2018-07-20-patched) fontloader from https://github.com/u-fischer/fontloader-archive/tree/master/archive

* create a luaotfload.conf in the search path with 

~~~~
[run]
fontloader= fontloader-reference-2018-07-20.lua;
~~~~

### with a lua function

~~~~
\documentclass{book}

\usepackage{fontspec}
\setmainfont{Coelacanth}
\newcommand\byunicode[1]{\directlua{
      for k, v in pairs(fonts.hashes.identifiers[font.current()].characters) do
          if v.unicode == #1 then
              tex.print(utf.char(k))
              break
          end
      end
 }}


\begin{document}

\byunicode{62860} \byunicode{\number"F58C}

\end{document}
~~~~

**Comment by u-fischer** [comment]
I uploaded a new version to ctan, it should be available tomorrow. If you want to try directly: Both the texmf-tree and the zip in the dev-branch contain the new files.

**Comment by ArTourter** [comment]
That fixes it for fontawesome. Thanks!

**Comment by mewtant** [comment]
Thanks for fixing this so quickly!  The updated `luaotfload` works perfectly.
