### ISSUE TITLE
VORG and vmtx table

### ISSUE THREAD

**Issue by h-kitagawa** [u-fischer/luaotfload#71]
(Perhaps ConTeXt ML is better place ...)

It seems that current fontloader of luaotfload skips to load the VORG table and topSideBearing in the vmtx table:
> ```
> readers.vorg=function(f,fontdata,specification)
>  reportskippedtable(f,fontdata,"vorg",specification.glyphs)
> end
> ```
> ```
> readers.vmtx=function(f,fontdata,specification)
>    ...
>   for i=0,nofmetrics-1 do
>    local glyph=glyphs[i]
>    vheight=readshort(f)
>    topsidebearing=readshort(f)
>    if vheight~=0 and vheight~=vdefault then
>     glyph.vheight=vheight
>    end
>   end
> ```

These informations are useful for vertical writing (in the LuaTeX-ja package).

**Comment by zauguin** [comment]
@h-kitagawa You're right, you would have to ask the ConTeXt team for this. But joust out of personal curiosity: Why do you need to access the sidebearings anyway?

**Comment by h-kitagawa** [comment]
> @h-kitagawa You're right, you would have to ask the ConTeXt team for this. 

Thanks, I'll ask them.

>Why do you need to access the sidebearings anyway?

To get a glyph's vertical origin. If the font does not have the VORG table, the vertical origin has to be computed from the bounding box and the top side bearing (in the vmtx table).
cf. https://docs.microsoft.com/en-us/typography/opentype/spec/vmtx

**Comment by h-kitagawa** [comment]
> you would have to ask the ConTeXt team for this

I asked Hans, and [v2.9902-2019-07-24](https://github.com/u-fischer/luaotfload/tree/v2.9902-2019-07-24) reads topSideBearing, thanks.

**Comment by u-fischer** [comment]
Oh nice side effect ;-), I actually created it because of another issue. I'm glad that it helped you too.
