### ISSUE TITLE
AfeySiddham problem on v.2.98

### ISSUE THREAD

**Issue by ijaradnam** [u-fischer/luaotfload#75]

**Comment by ijaradnam** [comment]
Ligatures containing rya have failed.
For example, grya, drya, trya, strya etc.

**Comment by u-fischer** [comment]
Please add a complete example demonstrating the problem. At best with screenshots showing the faulty and expected output - none of use write this script.

**Comment by ijaradnam** [comment]
The following sample is compiled by xelatex and lualatex. Results are attached.
`\documentclass[b5paper]{article}`
`\usepackage{fontspec}`
`\newfontfamily\deva[Script=Devanagari]{AfeySiddham}`
`\begin{document}`
`{\deva ग्र्यद्र्यत्र्यस्त्र्य}`
`\end{document}`
[luaotfload-lualatex.pdf](https://github.com/u-fischer/luaotfload/files/3455892/luaotfload-lualatex.pdf)
[luaotfload-xelatex.pdf](https://github.com/u-fischer/luaotfload/files/3455894/luaotfload-xelatex.pdf)

**Comment by u-fischer** [comment]
It doesn't work with context either. 

So imho your options are: 

* report it to the context mailing list with a context example (see https://github.com/u-fischer/luaotfload/issues/13) and hope that the fontloader gets corrected/updated.
* Or try with the features mentioned in #13.
* Or try a harfbuzz-enabled lualatex.   See https://tex.stackexchange.com/questions/493180/how-to-install-harftex-on-texlive.

**Comment by u-fischer** [comment]
This will have to wait for a luatex with harfbuzz.
