### ISSUE TITLE
Fontawesome doesn't work with new version

### ISSUE THREAD

**Issue by ArTourter** [u-fischer/luaotfload#8]
Hi,
Since the latest update using fontawesome characters do not appear in the compiled document with a warning in the log file

>   Missing character: There is no  (U+F003) in font FontAwesome!
>   {/usr/local/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (./test.aux))

```
\documentclass{article}
\usepackage{fontspec}
\usepackage{fontawesome}

\begin{document}

\faEnvelopeO{}

\end{document}
```
produces a blank page with just the page number.
reverting to version 47444 fixes the problem.

However, I think there might be a problem with the otf font itself which the previous version of luaotfload didn't catch, as the same document does compile with xelatex complaining that it cannot find the font. However, I am not familiar with xelatex and have never really been able to work with the fonts with it. If there is a problem with the fontawesome otf file, I wouldn't know where to start to identify unfortunately.

Greg

**Comment by u-fischer** [comment]
That's a the same problem as issue #7, so I'm closing the issue as duplicate. 

(The example works fine for me with xelatex, but I'm on windows. On linux you probably will have to adjust the fontconfig settings, see e.g. https://tex.stackexchange.com/a/257232/2388)

**Comment by u-fischer** [comment]
Side-remark: the fontawesome5 package is not affected by the change:

~~~~
\documentclass{article}
\usepackage{fontspec}
\usepackage{fontawesome5}

\begin{document}

\faEnvelopeOpen{}
\faEnvelope{}
\end{document}

~~~~
