### ISSUE TITLE
Devanagari output is not satisfactory

### ISSUE THREAD

**Issue by u-fischer** [u-fischer/luaotfload#9]
The output of devanagari is not good and should be improved. As can be seen in the examples below the problem is not with the generic fontloader -- its output is like the one in context (which is not completly identical to xetex but looks quite good). I suspect  that the problem is in luaotfload-features, which duplicates parts of font-ott but hasn't been updated/synched for quite some time. Another possibility is missing character data due to the stripped down luaotfload-characters.lua. 

## LaTeX example

~~~~
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage[english]{babel}
\newfontfamily\deva[Script=Devanagari]{NotoSansDevanagari-Regular.ttf}
\begin{document}

\begin{quotation}\deva
कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\\
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥ २-४७
\end{quotation}
\end{document}
~~~~

## xelatex output 

![xetex-noto-sanskrit](https://user-images.githubusercontent.com/4047173/46407370-03622280-c70f-11e8-88c3-189114feb2a2.PNG)

## lualatex output

![lualatex-noto-sanskrit](https://user-images.githubusercontent.com/4047173/46407371-08bf6d00-c70f-11e8-9b38-ad88ffda5e3b.PNG)

## plain with all the features context uses:

~~~~
\input luaotfload.sty
\font\deva={file:NotoSansDevanagari-Regular.ttf:mode=node;%
   language=dflt;script=deva;%
   +mark;+mkmk;+curs;+liga;+locl;+kern;+dist;%
   +abvm;+blwm;+nukt;+akhn;%
   +rphf;%
   +pres;%
   +abvs;%
   +blws;+psts;+haln;+calt;+rkrf;+blwf;+half;+vatu;+cjct;%
   }

    \deva कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।

मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥ २-४७

\bye
~~~~

![plain-bad-noto](https://user-images.githubusercontent.com/4047173/46412864-fb5eae80-c71f-11e8-902d-0e85e0d30dc5.PNG)

## context example

~~~~
\definefont [Deva][file:NotoSansDevanagari-Regular.ttf*devanagari-one]
\starttext
    \Deva कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\crlf
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥ २-४७
\stoptext
~~~~

![context-noto-sanskript](https://user-images.githubusercontent.com/4047173/46407391-1c6ad380-c70f-11e8-99f5-807280863bef.PNG)

## example with the generic / plain fontloader (format plainfontloader in the dev branch)

~~~~
\font\deva={file:NotoSansDevanagari-Regular.ttf:mode=node;%
   language=dflt;script=deva;%
   +mark;+mkmk;+curs;+liga;+locl;+kern;+dist;%
   +abvm;+blwm;+nukt;+akhn;%
   +rphf;%
   +pres;%
   +abvs;%
   +blws;+psts;+haln;+calt;+rkrf;+blwf;+half;+vatu;+cjct;%
   }
    \deva कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।

मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥ २-४७

\bye
~~~~

![plain-noto](https://user-images.githubusercontent.com/4047173/46411991-7ecad080-c71d-11e8-98c0-41cacef11e96.PNG)

**Comment by krishnakumarg1984** [comment]
This was fast. Thank you very much Ulrike.

**Comment by u-fischer** [comment]
With the new development version this latex examples looks like the context output:

~~~~
\documentclass[12pt]{article}
\usepackage{fontspec}
\usepackage[english]{babel}
\newfontscript{Devanagari}{deva,dev2} %need to force deva! 
\newfontfamily\deva[Script=Devanagari,
    ]{NotoSansDevanagari-Regular.ttf}
\begin{document}

\begin{quotation}\deva
कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\\
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥ २-४७
\end{quotation}
\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/46440932-4222c780-c765-11e8-931b-ccfa02017810.png)

**Comment by u-fischer** [comment]
Lualatex-output with siddhanta (above example with `\newfontfamily\deva[Script=Devanagari]{siddhanta.ttf}`) looks identical than the xelatex-output:

![image](https://user-images.githubusercontent.com/4047173/46470269-55ba4680-c7d6-11e8-94cc-5917a0405e46.png)

So the slight glitch above is font dependant. Perhaps Noto is missing a ligature or a variant has the wrong name ...

**Comment by krishnakumarg1984** [comment]
Well...I used Siddhanta for my PhD thesis submission on Oct 3, 2018. LuaLaTeX output looked very different then.

**Comment by krishnakumarg1984** [comment]
Ok....Commented too early.....sorry.  You have updated the font-loader.  Yes, looks like the issues with the engine are fixed. It is only the issue with the `noto` fonts. That Siddhanta is superior is not surprising, since it is an open-type Unicode font with advanced features.

**Comment by u-fischer** [comment]
@krishnakumarg1984  Yes. The change is currently only in the development branch. You should have asked a week earlier ;-). We can't know that a script is broken if nobody mentions it.

**Comment by krishnakumarg1984** [comment]
Hehe...understood. It is only a manuscript for viva examination.  The final upload will certainly benefit from this. Thank you for the amazing support.

**Comment by u-fischer** [comment]
With the newest context version there is a small glitch in the siddhanta output:

~~~~
\definefont [Deva][file:siddhanta.ttf*devanagari-one]
\starttext
    \Deva कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।\crlf
मा कर्मफलहेतुर्भूर्मा ते सङ्गोऽस्त्वकर्मणि॥ २-४७
\stoptext
~~~~

![context-glitch](https://user-images.githubusercontent.com/4047173/47207050-89769e00-d38a-11e8-989b-1e6ef8b2dc30.PNG)

## xelatex output:
![xelatex-sidd](https://user-images.githubusercontent.com/4047173/47207169-d5294780-d38a-11e8-93bf-042a2786f46f.PNG)

**Comment by u-fischer** [comment]
v 2.92 just uploaded to ctan improves deva and gives the state described here. Closing the issue. New problems should be put in new issues.

**Comment by krishnakumarg1984** [comment]
@u-fischer  Thank you for the keen interest in this issue. Much appreciate your efforts.
